/**

Generated by the following Solidity interface...
```solidity
interface BLS {
	error G1AddFailed();
	error G1MSMFailed();
	error G2AddFailed();
	error G2MSMFailed();
	error MapFp2ToG2Failed();
	error MapFpToG1Failed();
	error PairingFailed();
}
```

...which was generated by the following JSON ABI:
```json
[
  {
	"type": "error",
	"name": "G1AddFailed",
	"inputs": []
  },
  {
	"type": "error",
	"name": "G1MSMFailed",
	"inputs": []
  },
  {
	"type": "error",
	"name": "G2AddFailed",
	"inputs": []
  },
  {
	"type": "error",
	"name": "G2MSMFailed",
	"inputs": []
  },
  {
	"type": "error",
	"name": "MapFp2ToG2Failed",
	"inputs": []
  },
  {
	"type": "error",
	"name": "MapFpToG1Failed",
	"inputs": []
  },
  {
	"type": "error",
	"name": "PairingFailed",
	"inputs": []
  }
]
```*/
#[allow(
	non_camel_case_types,
	non_snake_case,
	clippy::pub_underscore_fields,
	clippy::style,
	clippy::empty_structs_with_brackets
)]
pub mod BLS {
	use super::*;
	use alloy::sol_types as alloy_sol_types;
	/// The creation / init bytecode of the contract.
    ///
    /// ```text
    ///0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207f7fcd979062fcba9c18b80978361e629cb8bf8104440c6766a66e74c837086364736f6c63430008190033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"`U`2`\x0B\x82\x82\x829\x80Q_\x1A`s\x14`&WcNH{q`\xE0\x1B_R_`\x04R`$_\xFD[0_R`s\x81S\x82\x81\xF3\xFEs\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x000\x14`\x80`@R_\x80\xFD\xFE\xA2dipfsX\"\x12 \x7F\x7F\xCD\x97\x90b\xFC\xBA\x9C\x18\xB8\tx6\x1Eb\x9C\xB8\xBF\x81\x04D\x0Cgf\xA6nt\xC87\x08cdsolcC\0\x08\x19\x003",
    );
	/// The runtime bytecode of the contract, as deployed on the network.
    ///
    /// ```text
    ///0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207f7fcd979062fcba9c18b80978361e629cb8bf8104440c6766a66e74c837086364736f6c63430008190033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static DEPLOYED_BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"s\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x000\x14`\x80`@R_\x80\xFD\xFE\xA2dipfsX\"\x12 \x7F\x7F\xCD\x97\x90b\xFC\xBA\x9C\x18\xB8\tx6\x1Eb\x9C\xB8\xBF\x81\x04D\x0Cgf\xA6nt\xC87\x08cdsolcC\0\x08\x19\x003",
    );
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `G1AddFailed()` and selector `0xd6cc76eb`.
	```solidity
	error G1AddFailed();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct G1AddFailed;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<G1AddFailed> for UnderlyingRustTuple<'_> {
			fn from(value: G1AddFailed) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for G1AddFailed {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for G1AddFailed {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "G1AddFailed()";
			const SELECTOR: [u8; 4] = [214u8, 204u8, 118u8, 235u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `G1MSMFailed()` and selector `0x5f776986`.
	```solidity
	error G1MSMFailed();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct G1MSMFailed;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<G1MSMFailed> for UnderlyingRustTuple<'_> {
			fn from(value: G1MSMFailed) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for G1MSMFailed {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for G1MSMFailed {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "G1MSMFailed()";
			const SELECTOR: [u8; 4] = [95u8, 119u8, 105u8, 134u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `G2AddFailed()` and selector `0xc55e5e33`.
	```solidity
	error G2AddFailed();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct G2AddFailed;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<G2AddFailed> for UnderlyingRustTuple<'_> {
			fn from(value: G2AddFailed) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for G2AddFailed {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for G2AddFailed {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "G2AddFailed()";
			const SELECTOR: [u8; 4] = [197u8, 94u8, 94u8, 51u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `G2MSMFailed()` and selector `0xe3dc5425`.
	```solidity
	error G2MSMFailed();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct G2MSMFailed;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<G2MSMFailed> for UnderlyingRustTuple<'_> {
			fn from(value: G2MSMFailed) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for G2MSMFailed {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for G2MSMFailed {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "G2MSMFailed()";
			const SELECTOR: [u8; 4] = [227u8, 220u8, 84u8, 37u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `MapFp2ToG2Failed()` and selector `0x89083b91`.
	```solidity
	error MapFp2ToG2Failed();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct MapFp2ToG2Failed;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<MapFp2ToG2Failed> for UnderlyingRustTuple<'_> {
			fn from(value: MapFp2ToG2Failed) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for MapFp2ToG2Failed {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for MapFp2ToG2Failed {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "MapFp2ToG2Failed()";
			const SELECTOR: [u8; 4] = [137u8, 8u8, 59u8, 145u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `MapFpToG1Failed()` and selector `0x24a289fc`.
	```solidity
	error MapFpToG1Failed();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct MapFpToG1Failed;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<MapFpToG1Failed> for UnderlyingRustTuple<'_> {
			fn from(value: MapFpToG1Failed) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for MapFpToG1Failed {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for MapFpToG1Failed {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "MapFpToG1Failed()";
			const SELECTOR: [u8; 4] = [36u8, 162u8, 137u8, 252u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `PairingFailed()` and selector `0x4df45e2f`.
	```solidity
	error PairingFailed();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct PairingFailed;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<PairingFailed> for UnderlyingRustTuple<'_> {
			fn from(value: PairingFailed) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for PairingFailed {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for PairingFailed {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "PairingFailed()";
			const SELECTOR: [u8; 4] = [77u8, 244u8, 94u8, 47u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	///Container for all the [`BLS`](self) custom errors.
	#[derive(Clone, serde::Serialize, serde::Deserialize, Debug, PartialEq, Eq, Hash)]
	pub enum BLSErrors {
		#[allow(missing_docs)]
		G1AddFailed(G1AddFailed),
		#[allow(missing_docs)]
		G1MSMFailed(G1MSMFailed),
		#[allow(missing_docs)]
		G2AddFailed(G2AddFailed),
		#[allow(missing_docs)]
		G2MSMFailed(G2MSMFailed),
		#[allow(missing_docs)]
		MapFp2ToG2Failed(MapFp2ToG2Failed),
		#[allow(missing_docs)]
		MapFpToG1Failed(MapFpToG1Failed),
		#[allow(missing_docs)]
		PairingFailed(PairingFailed),
	}
	impl BLSErrors {
		/// All the selectors of this enum.
		///
		/// Note that the selectors might not be in the same order as the variants.
		/// No guarantees are made about the order of the selectors.
		///
		/// Prefer using `SolInterface` methods instead.
		pub const SELECTORS: &'static [[u8; 4usize]] = &[
			[36u8, 162u8, 137u8, 252u8],
			[77u8, 244u8, 94u8, 47u8],
			[95u8, 119u8, 105u8, 134u8],
			[137u8, 8u8, 59u8, 145u8],
			[197u8, 94u8, 94u8, 51u8],
			[214u8, 204u8, 118u8, 235u8],
			[227u8, 220u8, 84u8, 37u8],
		];
		/// The names of the variants in the same order as `SELECTORS`.
		pub const VARIANT_NAMES: &'static [&'static str] = &[
			::core::stringify!(MapFpToG1Failed),
			::core::stringify!(PairingFailed),
			::core::stringify!(G1MSMFailed),
			::core::stringify!(MapFp2ToG2Failed),
			::core::stringify!(G2AddFailed),
			::core::stringify!(G1AddFailed),
			::core::stringify!(G2MSMFailed),
		];
		/// The signatures in the same order as `SELECTORS`.
		pub const SIGNATURES: &'static [&'static str] = &[
			<MapFpToG1Failed as alloy_sol_types::SolError>::SIGNATURE,
			<PairingFailed as alloy_sol_types::SolError>::SIGNATURE,
			<G1MSMFailed as alloy_sol_types::SolError>::SIGNATURE,
			<MapFp2ToG2Failed as alloy_sol_types::SolError>::SIGNATURE,
			<G2AddFailed as alloy_sol_types::SolError>::SIGNATURE,
			<G1AddFailed as alloy_sol_types::SolError>::SIGNATURE,
			<G2MSMFailed as alloy_sol_types::SolError>::SIGNATURE,
		];
		/// Returns the signature for the given selector, if known.
		#[inline]
		pub fn signature_by_selector(selector: [u8; 4usize]) -> ::core::option::Option<&'static str> {
			match Self::SELECTORS.binary_search(&selector) {
				::core::result::Result::Ok(idx) => ::core::option::Option::Some(Self::SIGNATURES[idx]),
				::core::result::Result::Err(_) => ::core::option::Option::None,
			}
		}
		/// Returns the enum variant name for the given selector, if known.
		#[inline]
		pub fn name_by_selector(selector: [u8; 4usize]) -> ::core::option::Option<&'static str> {
			let sig = Self::signature_by_selector(selector)?;
			sig.split_once('(').map(|(name, _)| name)
		}
	}
	#[automatically_derived]
	impl alloy_sol_types::SolInterface for BLSErrors {
		const NAME: &'static str = "BLSErrors";
		const MIN_DATA_LENGTH: usize = 0usize;
		const COUNT: usize = 7usize;
		#[inline]
		fn selector(&self) -> [u8; 4] {
			match self {
				Self::G1AddFailed(_) => <G1AddFailed as alloy_sol_types::SolError>::SELECTOR,
				Self::G1MSMFailed(_) => <G1MSMFailed as alloy_sol_types::SolError>::SELECTOR,
				Self::G2AddFailed(_) => <G2AddFailed as alloy_sol_types::SolError>::SELECTOR,
				Self::G2MSMFailed(_) => <G2MSMFailed as alloy_sol_types::SolError>::SELECTOR,
				Self::MapFp2ToG2Failed(_) => <MapFp2ToG2Failed as alloy_sol_types::SolError>::SELECTOR,
				Self::MapFpToG1Failed(_) => <MapFpToG1Failed as alloy_sol_types::SolError>::SELECTOR,
				Self::PairingFailed(_) => <PairingFailed as alloy_sol_types::SolError>::SELECTOR,
			}
		}
		#[inline]
		fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
			Self::SELECTORS.get(i).copied()
		}
		#[inline]
		fn valid_selector(selector: [u8; 4]) -> bool {
			Self::SELECTORS.binary_search(&selector).is_ok()
		}
		#[inline]
		#[allow(non_snake_case)]
		fn abi_decode_raw(selector: [u8; 4], data: &[u8]) -> alloy_sol_types::Result<Self> {
			static DECODE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<BLSErrors>] = &[
				{
					fn MapFpToG1Failed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<MapFpToG1Failed as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(BLSErrors::MapFpToG1Failed)
					}
					MapFpToG1Failed
				},
				{
					fn PairingFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<PairingFailed as alloy_sol_types::SolError>::abi_decode_raw(data).map(BLSErrors::PairingFailed)
					}
					PairingFailed
				},
				{
					fn G1MSMFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<G1MSMFailed as alloy_sol_types::SolError>::abi_decode_raw(data).map(BLSErrors::G1MSMFailed)
					}
					G1MSMFailed
				},
				{
					fn MapFp2ToG2Failed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<MapFp2ToG2Failed as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(BLSErrors::MapFp2ToG2Failed)
					}
					MapFp2ToG2Failed
				},
				{
					fn G2AddFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<G2AddFailed as alloy_sol_types::SolError>::abi_decode_raw(data).map(BLSErrors::G2AddFailed)
					}
					G2AddFailed
				},
				{
					fn G1AddFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<G1AddFailed as alloy_sol_types::SolError>::abi_decode_raw(data).map(BLSErrors::G1AddFailed)
					}
					G1AddFailed
				},
				{
					fn G2MSMFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<G2MSMFailed as alloy_sol_types::SolError>::abi_decode_raw(data).map(BLSErrors::G2MSMFailed)
					}
					G2MSMFailed
				},
			];
			let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
				return Err(alloy_sol_types::Error::unknown_selector(
					<Self as alloy_sol_types::SolInterface>::NAME,
					selector,
				));
			};
			DECODE_SHIMS[idx](data)
		}
		#[inline]
		#[allow(non_snake_case)]
		fn abi_decode_raw_validate(selector: [u8; 4], data: &[u8]) -> alloy_sol_types::Result<Self> {
			static DECODE_VALIDATE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<BLSErrors>] = &[
				{
					fn MapFpToG1Failed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<MapFpToG1Failed as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(BLSErrors::MapFpToG1Failed)
					}
					MapFpToG1Failed
				},
				{
					fn PairingFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<PairingFailed as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(BLSErrors::PairingFailed)
					}
					PairingFailed
				},
				{
					fn G1MSMFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<G1MSMFailed as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(BLSErrors::G1MSMFailed)
					}
					G1MSMFailed
				},
				{
					fn MapFp2ToG2Failed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<MapFp2ToG2Failed as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(BLSErrors::MapFp2ToG2Failed)
					}
					MapFp2ToG2Failed
				},
				{
					fn G2AddFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<G2AddFailed as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(BLSErrors::G2AddFailed)
					}
					G2AddFailed
				},
				{
					fn G1AddFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<G1AddFailed as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(BLSErrors::G1AddFailed)
					}
					G1AddFailed
				},
				{
					fn G2MSMFailed(data: &[u8]) -> alloy_sol_types::Result<BLSErrors> {
						<G2MSMFailed as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(BLSErrors::G2MSMFailed)
					}
					G2MSMFailed
				},
			];
			let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
				return Err(alloy_sol_types::Error::unknown_selector(
					<Self as alloy_sol_types::SolInterface>::NAME,
					selector,
				));
			};
			DECODE_VALIDATE_SHIMS[idx](data)
		}
		#[inline]
		fn abi_encoded_size(&self) -> usize {
			match self {
				Self::G1AddFailed(inner) => <G1AddFailed as alloy_sol_types::SolError>::abi_encoded_size(inner),
				Self::G1MSMFailed(inner) => <G1MSMFailed as alloy_sol_types::SolError>::abi_encoded_size(inner),
				Self::G2AddFailed(inner) => <G2AddFailed as alloy_sol_types::SolError>::abi_encoded_size(inner),
				Self::G2MSMFailed(inner) => <G2MSMFailed as alloy_sol_types::SolError>::abi_encoded_size(inner),
				Self::MapFp2ToG2Failed(inner) => {
					<MapFp2ToG2Failed as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::MapFpToG1Failed(inner) => <MapFpToG1Failed as alloy_sol_types::SolError>::abi_encoded_size(inner),
				Self::PairingFailed(inner) => <PairingFailed as alloy_sol_types::SolError>::abi_encoded_size(inner),
			}
		}
		#[inline]
		fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
			match self {
				Self::G1AddFailed(inner) => <G1AddFailed as alloy_sol_types::SolError>::abi_encode_raw(inner, out),
				Self::G1MSMFailed(inner) => <G1MSMFailed as alloy_sol_types::SolError>::abi_encode_raw(inner, out),
				Self::G2AddFailed(inner) => <G2AddFailed as alloy_sol_types::SolError>::abi_encode_raw(inner, out),
				Self::G2MSMFailed(inner) => <G2MSMFailed as alloy_sol_types::SolError>::abi_encode_raw(inner, out),
				Self::MapFp2ToG2Failed(inner) => {
					<MapFp2ToG2Failed as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::MapFpToG1Failed(inner) => {
					<MapFpToG1Failed as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::PairingFailed(inner) => <PairingFailed as alloy_sol_types::SolError>::abi_encode_raw(inner, out),
			}
		}
	}
	use alloy::contract as alloy_contract;
	/**Creates a new wrapper around an on-chain [`BLS`](self) contract instance.

	See the [wrapper's documentation](`BLSInstance`) for more details.*/
	#[inline]
	pub const fn new<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		address: alloy_sol_types::private::Address,
		__provider: P,
	) -> BLSInstance<P, N> {
		BLSInstance::<P, N>::new(address, __provider)
	}
	/**Deploys this contract using the given `provider` and constructor arguments, if any.

	Returns a new instance of the contract, if the deployment was successful.

	For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
	#[inline]
	pub fn deploy<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		__provider: P,
	) -> impl ::core::future::Future<Output = alloy_contract::Result<BLSInstance<P, N>>> {
		BLSInstance::<P, N>::deploy(__provider)
	}
	/**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
	and constructor arguments, if any.

	This is a simple wrapper around creating a `RawCallBuilder` with the data set to
	the bytecode concatenated with the constructor's ABI-encoded arguments.*/
	#[inline]
	pub fn deploy_builder<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		__provider: P,
	) -> alloy_contract::RawCallBuilder<P, N> {
		BLSInstance::<P, N>::deploy_builder(__provider)
	}
	/**A [`BLS`](self) instance.

	Contains type-safe methods for interacting with an on-chain instance of the
	[`BLS`](self) contract located at a given `address`, using a given
	provider `P`.

	If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
	documentation on how to provide it), the `deploy` and `deploy_builder` methods can
	be used to deploy a new instance of the contract.

	See the [module-level documentation](self) for all the available methods.*/
	#[derive(Clone)]
	pub struct BLSInstance<P, N = alloy_contract::private::Ethereum> {
		address: alloy_sol_types::private::Address,
		provider: P,
		_network: ::core::marker::PhantomData<N>,
	}
	#[automatically_derived]
	impl<P, N> ::core::fmt::Debug for BLSInstance<P, N> {
		#[inline]
		fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
			f.debug_tuple("BLSInstance").field(&self.address).finish()
		}
	}
	/// Instantiation and getters/setters.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> BLSInstance<P, N> {
		/**Creates a new wrapper around an on-chain [`BLS`](self) contract instance.

		See the [wrapper's documentation](`BLSInstance`) for more details.*/
		#[inline]
		pub const fn new(address: alloy_sol_types::private::Address, __provider: P) -> Self {
			Self { address, provider: __provider, _network: ::core::marker::PhantomData }
		}
		/**Deploys this contract using the given `provider` and constructor arguments, if any.

		Returns a new instance of the contract, if the deployment was successful.

		For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
		#[inline]
		pub async fn deploy(__provider: P) -> alloy_contract::Result<BLSInstance<P, N>> {
			let call_builder = Self::deploy_builder(__provider);
			let contract_address = call_builder.deploy().await?;
			Ok(Self::new(contract_address, call_builder.provider))
		}
		/**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
		and constructor arguments, if any.

		This is a simple wrapper around creating a `RawCallBuilder` with the data set to
		the bytecode concatenated with the constructor's ABI-encoded arguments.*/
		#[inline]
		pub fn deploy_builder(__provider: P) -> alloy_contract::RawCallBuilder<P, N> {
			alloy_contract::RawCallBuilder::new_raw_deploy(__provider, ::core::clone::Clone::clone(&BYTECODE))
		}
		/// Returns a reference to the address.
		#[inline]
		pub const fn address(&self) -> &alloy_sol_types::private::Address {
			&self.address
		}
		/// Sets the address.
		#[inline]
		pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
			self.address = address;
		}
		/// Sets the address and returns `self`.
		pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
			self.set_address(address);
			self
		}
		/// Returns a reference to the provider.
		#[inline]
		pub const fn provider(&self) -> &P {
			&self.provider
		}
	}
	impl<P: ::core::clone::Clone, N> BLSInstance<&P, N> {
		/// Clones the provider and returns a new instance with the cloned provider.
		#[inline]
		pub fn with_cloned_provider(self) -> BLSInstance<P, N> {
			BLSInstance {
				address: self.address,
				provider: ::core::clone::Clone::clone(&self.provider),
				_network: ::core::marker::PhantomData,
			}
		}
	}
	/// Function calls.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> BLSInstance<P, N> {
		/// Creates a new call builder using this contract instance's provider and address.
		///
		/// Note that the call can be any function call, not just those defined in this
		/// contract. Prefer using the other methods for building type-safe contract calls.
		pub fn call_builder<C: alloy_sol_types::SolCall>(&self, call: &C) -> alloy_contract::SolCallBuilder<&P, C, N> {
			alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
		}
	}
	/// Event filters.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> BLSInstance<P, N> {
		/// Creates a new event filter using this contract instance's provider and address.
		///
		/// Note that the type can be any event, not just those defined in this contract.
		/// Prefer using the other methods for building type-safe event filters.
		pub fn event_filter<E: alloy_sol_types::SolEvent>(&self) -> alloy_contract::Event<&P, E, N> {
			alloy_contract::Event::new_sol(&self.provider, &self.address)
		}
	}
}
