/**

Generated by the following Solidity interface...
```solidity
interface Foo {
	function generateTree(bytes32[] memory leaves) external pure returns (bytes32);
}
```

...which was generated by the following JSON ABI:
```json
[
  {
	"type": "function",
	"name": "generateTree",
	"inputs": [
	  {
		"name": "leaves",
		"type": "bytes32[]",
		"internalType": "bytes32[]"
	  }
	],
	"outputs": [
	  {
		"name": "",
		"type": "bytes32",
		"internalType": "bytes32"
	  }
	],
	"stateMutability": "pure"
  }
]
```*/
#[allow(
	non_camel_case_types,
	non_snake_case,
	clippy::pub_underscore_fields,
	clippy::style,
	clippy::empty_structs_with_brackets
)]
pub mod Foo {
	use super::*;
	use alloy::sol_types as alloy_sol_types;
	/// The creation / init bytecode of the contract.
    ///
    /// ```text
    ///0x6080604052348015600e575f80fd5b5061029d8061001c5f395ff3fe608060405234801561000f575f80fd5b5060043610610029575f3560e01c80639ffeea521461002d575b5f80fd5b61004061003b3660046101f8565b610052565b60405190815260200160405180910390f35b5f61008e8383808060200260200160405190810160405280939291908181526020018383602002808284375f9201919091525061009592505050565b9392505050565b5f6100af6100aa6100a5846100b5565b6100c1565b610161565b92915050565b60606100af825f61017e565b6040518151806100d85763e7171dc45f526004601cfd5b600181820103808352602083018160051b81019150816040528260051b60200160205b80870151818503526020810190508181036100fb57505060028310610159576002830360051b91505b818001810160208181015160409283015180821060051b908152909118525f2081830152811561015957602082039150610124565b505050919050565b6020810151815161017957637a856a385f526004601cfd5b919050565b6040518251806101955763e7171dc45f526004601cfd5b60015b818110156101a7578001610198565b8083528060051b60200183016040528483038260051b602087010192508160051b60208701019150845f52602086015b838110810251828201526020810190508281036101d7575050505092915050565b5f8060208385031215610209575f80fd5b823567ffffffffffffffff80821115610220575f80fd5b818501915085601f830112610233575f80fd5b813581811115610241575f80fd5b8660208260051b8501011115610255575f80fd5b6020929092019691955090935050505056fea264697066735822122076fc6f4018a43f41e3f58e3435c8b661a923e77402fa1e128699e846806854ea64736f6c63430008190033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"`\x80`@R4\x80\x15`\x0EW_\x80\xFD[Pa\x02\x9D\x80a\0\x1C_9_\xF3\xFE`\x80`@R4\x80\x15a\0\x0FW_\x80\xFD[P`\x046\x10a\0)W_5`\xE0\x1C\x80c\x9F\xFE\xEAR\x14a\0-W[_\x80\xFD[a\0@a\0;6`\x04a\x01\xF8V[a\0RV[`@Q\x90\x81R` \x01`@Q\x80\x91\x03\x90\xF3[_a\0\x8E\x83\x83\x80\x80` \x02` \x01`@Q\x90\x81\x01`@R\x80\x93\x92\x91\x90\x81\x81R` \x01\x83\x83` \x02\x80\x82\x847_\x92\x01\x91\x90\x91RPa\0\x95\x92PPPV[\x93\x92PPPV[_a\0\xAFa\0\xAAa\0\xA5\x84a\0\xB5V[a\0\xC1V[a\x01aV[\x92\x91PPV[``a\0\xAF\x82_a\x01~V[`@Q\x81Q\x80a\0\xD8Wc\xE7\x17\x1D\xC4_R`\x04`\x1C\xFD[`\x01\x81\x82\x01\x03\x80\x83R` \x83\x01\x81`\x05\x1B\x81\x01\x91P\x81`@R\x82`\x05\x1B` \x01` [\x80\x87\x01Q\x81\x85\x03R` \x81\x01\x90P\x81\x81\x03a\0\xFBWPP`\x02\x83\x10a\x01YW`\x02\x83\x03`\x05\x1B\x91P[\x81\x80\x01\x81\x01` \x81\x81\x01Q`@\x92\x83\x01Q\x80\x82\x10`\x05\x1B\x90\x81R\x90\x91\x18R_ \x81\x83\x01R\x81\x15a\x01YW` \x82\x03\x91Pa\x01$V[PPP\x91\x90PV[` \x81\x01Q\x81Qa\x01yWcz\x85j8_R`\x04`\x1C\xFD[\x91\x90PV[`@Q\x82Q\x80a\x01\x95Wc\xE7\x17\x1D\xC4_R`\x04`\x1C\xFD[`\x01[\x81\x81\x10\x15a\x01\xA7W\x80\x01a\x01\x98V[\x80\x83R\x80`\x05\x1B` \x01\x83\x01`@R\x84\x83\x03\x82`\x05\x1B` \x87\x01\x01\x92P\x81`\x05\x1B` \x87\x01\x01\x91P\x84_R` \x86\x01[\x83\x81\x10\x81\x02Q\x82\x82\x01R` \x81\x01\x90P\x82\x81\x03a\x01\xD7WPPPP\x92\x91PPV[_\x80` \x83\x85\x03\x12\x15a\x02\tW_\x80\xFD[\x825g\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x80\x82\x11\x15a\x02 W_\x80\xFD[\x81\x85\x01\x91P\x85`\x1F\x83\x01\x12a\x023W_\x80\xFD[\x815\x81\x81\x11\x15a\x02AW_\x80\xFD[\x86` \x82`\x05\x1B\x85\x01\x01\x11\x15a\x02UW_\x80\xFD[` \x92\x90\x92\x01\x96\x91\x95P\x90\x93PPPPV\xFE\xA2dipfsX\"\x12 v\xFCo@\x18\xA4?A\xE3\xF5\x8E45\xC8\xB6a\xA9#\xE7t\x02\xFA\x1E\x12\x86\x99\xE8F\x80hT\xEAdsolcC\0\x08\x19\x003",
    );
	/// The runtime bytecode of the contract, as deployed on the network.
    ///
    /// ```text
    ///0x608060405234801561000f575f80fd5b5060043610610029575f3560e01c80639ffeea521461002d575b5f80fd5b61004061003b3660046101f8565b610052565b60405190815260200160405180910390f35b5f61008e8383808060200260200160405190810160405280939291908181526020018383602002808284375f9201919091525061009592505050565b9392505050565b5f6100af6100aa6100a5846100b5565b6100c1565b610161565b92915050565b60606100af825f61017e565b6040518151806100d85763e7171dc45f526004601cfd5b600181820103808352602083018160051b81019150816040528260051b60200160205b80870151818503526020810190508181036100fb57505060028310610159576002830360051b91505b818001810160208181015160409283015180821060051b908152909118525f2081830152811561015957602082039150610124565b505050919050565b6020810151815161017957637a856a385f526004601cfd5b919050565b6040518251806101955763e7171dc45f526004601cfd5b60015b818110156101a7578001610198565b8083528060051b60200183016040528483038260051b602087010192508160051b60208701019150845f52602086015b838110810251828201526020810190508281036101d7575050505092915050565b5f8060208385031215610209575f80fd5b823567ffffffffffffffff80821115610220575f80fd5b818501915085601f830112610233575f80fd5b813581811115610241575f80fd5b8660208260051b8501011115610255575f80fd5b6020929092019691955090935050505056fea264697066735822122076fc6f4018a43f41e3f58e3435c8b661a923e77402fa1e128699e846806854ea64736f6c63430008190033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static DEPLOYED_BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"`\x80`@R4\x80\x15a\0\x0FW_\x80\xFD[P`\x046\x10a\0)W_5`\xE0\x1C\x80c\x9F\xFE\xEAR\x14a\0-W[_\x80\xFD[a\0@a\0;6`\x04a\x01\xF8V[a\0RV[`@Q\x90\x81R` \x01`@Q\x80\x91\x03\x90\xF3[_a\0\x8E\x83\x83\x80\x80` \x02` \x01`@Q\x90\x81\x01`@R\x80\x93\x92\x91\x90\x81\x81R` \x01\x83\x83` \x02\x80\x82\x847_\x92\x01\x91\x90\x91RPa\0\x95\x92PPPV[\x93\x92PPPV[_a\0\xAFa\0\xAAa\0\xA5\x84a\0\xB5V[a\0\xC1V[a\x01aV[\x92\x91PPV[``a\0\xAF\x82_a\x01~V[`@Q\x81Q\x80a\0\xD8Wc\xE7\x17\x1D\xC4_R`\x04`\x1C\xFD[`\x01\x81\x82\x01\x03\x80\x83R` \x83\x01\x81`\x05\x1B\x81\x01\x91P\x81`@R\x82`\x05\x1B` \x01` [\x80\x87\x01Q\x81\x85\x03R` \x81\x01\x90P\x81\x81\x03a\0\xFBWPP`\x02\x83\x10a\x01YW`\x02\x83\x03`\x05\x1B\x91P[\x81\x80\x01\x81\x01` \x81\x81\x01Q`@\x92\x83\x01Q\x80\x82\x10`\x05\x1B\x90\x81R\x90\x91\x18R_ \x81\x83\x01R\x81\x15a\x01YW` \x82\x03\x91Pa\x01$V[PPP\x91\x90PV[` \x81\x01Q\x81Qa\x01yWcz\x85j8_R`\x04`\x1C\xFD[\x91\x90PV[`@Q\x82Q\x80a\x01\x95Wc\xE7\x17\x1D\xC4_R`\x04`\x1C\xFD[`\x01[\x81\x81\x10\x15a\x01\xA7W\x80\x01a\x01\x98V[\x80\x83R\x80`\x05\x1B` \x01\x83\x01`@R\x84\x83\x03\x82`\x05\x1B` \x87\x01\x01\x92P\x81`\x05\x1B` \x87\x01\x01\x91P\x84_R` \x86\x01[\x83\x81\x10\x81\x02Q\x82\x82\x01R` \x81\x01\x90P\x82\x81\x03a\x01\xD7WPPPP\x92\x91PPV[_\x80` \x83\x85\x03\x12\x15a\x02\tW_\x80\xFD[\x825g\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x80\x82\x11\x15a\x02 W_\x80\xFD[\x81\x85\x01\x91P\x85`\x1F\x83\x01\x12a\x023W_\x80\xFD[\x815\x81\x81\x11\x15a\x02AW_\x80\xFD[\x86` \x82`\x05\x1B\x85\x01\x01\x11\x15a\x02UW_\x80\xFD[` \x92\x90\x92\x01\x96\x91\x95P\x90\x93PPPPV\xFE\xA2dipfsX\"\x12 v\xFCo@\x18\xA4?A\xE3\xF5\x8E45\xC8\xB6a\xA9#\xE7t\x02\xFA\x1E\x12\x86\x99\xE8F\x80hT\xEAdsolcC\0\x08\x19\x003",
    );
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Function with signature `generateTree(bytes32[])` and selector `0x9ffeea52`.
	```solidity
	function generateTree(bytes32[] memory leaves) external pure returns (bytes32);
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct generateTreeCall {
		#[allow(missing_docs)]
		pub leaves: alloy::sol_types::private::Vec<alloy::sol_types::private::FixedBytes<32>>,
	}
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	///Container type for the return parameters of the [`generateTree(bytes32[])`](generateTreeCall) function.
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct generateTreeReturn {
		#[allow(missing_docs)]
		pub _0: alloy::sol_types::private::FixedBytes<32>,
	}
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		{
			#[doc(hidden)]
			#[allow(dead_code)]
			type UnderlyingSolTuple<'a> =
				(alloy::sol_types::sol_data::Array<alloy::sol_types::sol_data::FixedBytes<32>>,);
			#[doc(hidden)]
			type UnderlyingRustTuple<'a> = (alloy::sol_types::private::Vec<alloy::sol_types::private::FixedBytes<32>>,);
			#[cfg(test)]
			#[allow(dead_code, unreachable_patterns)]
			fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
				match _t {
					alloy_sol_types::private::AssertTypeEq::<
						<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
					>(_) => {}
				}
			}
			#[automatically_derived]
			#[doc(hidden)]
			impl ::core::convert::From<generateTreeCall> for UnderlyingRustTuple<'_> {
				fn from(value: generateTreeCall) -> Self {
					(value.leaves,)
				}
			}
			#[automatically_derived]
			#[doc(hidden)]
			impl ::core::convert::From<UnderlyingRustTuple<'_>> for generateTreeCall {
				fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
					Self { leaves: tuple.0 }
				}
			}
		}
		{
			#[doc(hidden)]
			#[allow(dead_code)]
			type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<32>,);
			#[doc(hidden)]
			type UnderlyingRustTuple<'a> = (alloy::sol_types::private::FixedBytes<32>,);
			#[cfg(test)]
			#[allow(dead_code, unreachable_patterns)]
			fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
				match _t {
					alloy_sol_types::private::AssertTypeEq::<
						<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
					>(_) => {}
				}
			}
			#[automatically_derived]
			#[doc(hidden)]
			impl ::core::convert::From<generateTreeReturn> for UnderlyingRustTuple<'_> {
				fn from(value: generateTreeReturn) -> Self {
					(value._0,)
				}
			}
			#[automatically_derived]
			#[doc(hidden)]
			impl ::core::convert::From<UnderlyingRustTuple<'_>> for generateTreeReturn {
				fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
					Self { _0: tuple.0 }
				}
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolCall for generateTreeCall {
			type Parameters<'a> = (alloy::sol_types::sol_data::Array<alloy::sol_types::sol_data::FixedBytes<32>>,);
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			type Return = alloy::sol_types::private::FixedBytes<32>;
			type ReturnTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<32>,);
			type ReturnToken<'a> = <Self::ReturnTuple<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "generateTree(bytes32[])";
			const SELECTOR: [u8; 4] = [159u8, 254u8, 234u8, 82u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				(
                    <alloy::sol_types::sol_data::Array<
                        alloy::sol_types::sol_data::FixedBytes<32>,
                    > as alloy_sol_types::SolType>::tokenize(&self.leaves),
                )
			}
			#[inline]
			fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
				(<alloy::sol_types::sol_data::FixedBytes<32> as alloy_sol_types::SolType>::tokenize(ret),)
			}
			#[inline]
			fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
				<Self::ReturnTuple<'_> as alloy_sol_types::SolType>::abi_decode_sequence(data).map(|r| {
					let r: generateTreeReturn = r.into();
					r._0
				})
			}
			#[inline]
			fn abi_decode_returns_validate(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
				<Self::ReturnTuple<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(|r| {
					let r: generateTreeReturn = r.into();
					r._0
				})
			}
		}
	};
	///Container for all the [`Foo`](self) function calls.
	#[derive(Clone, serde::Serialize, serde::Deserialize)]
	pub enum FooCalls {
		#[allow(missing_docs)]
		generateTree(generateTreeCall),
	}
	impl FooCalls {
		/// All the selectors of this enum.
		///
		/// Note that the selectors might not be in the same order as the variants.
		/// No guarantees are made about the order of the selectors.
		///
		/// Prefer using `SolInterface` methods instead.
		pub const SELECTORS: &'static [[u8; 4usize]] = &[[159u8, 254u8, 234u8, 82u8]];
		/// The names of the variants in the same order as `SELECTORS`.
		pub const VARIANT_NAMES: &'static [&'static str] = &[::core::stringify!(generateTree)];
		/// The signatures in the same order as `SELECTORS`.
		pub const SIGNATURES: &'static [&'static str] = &[<generateTreeCall as alloy_sol_types::SolCall>::SIGNATURE];
		/// Returns the signature for the given selector, if known.
		#[inline]
		pub fn signature_by_selector(selector: [u8; 4usize]) -> ::core::option::Option<&'static str> {
			match Self::SELECTORS.binary_search(&selector) {
				::core::result::Result::Ok(idx) => ::core::option::Option::Some(Self::SIGNATURES[idx]),
				::core::result::Result::Err(_) => ::core::option::Option::None,
			}
		}
		/// Returns the enum variant name for the given selector, if known.
		#[inline]
		pub fn name_by_selector(selector: [u8; 4usize]) -> ::core::option::Option<&'static str> {
			let sig = Self::signature_by_selector(selector)?;
			sig.split_once('(').map(|(name, _)| name)
		}
	}
	#[automatically_derived]
	impl alloy_sol_types::SolInterface for FooCalls {
		const NAME: &'static str = "FooCalls";
		const MIN_DATA_LENGTH: usize = 64usize;
		const COUNT: usize = 1usize;
		#[inline]
		fn selector(&self) -> [u8; 4] {
			match self {
				Self::generateTree(_) => <generateTreeCall as alloy_sol_types::SolCall>::SELECTOR,
			}
		}
		#[inline]
		fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
			Self::SELECTORS.get(i).copied()
		}
		#[inline]
		fn valid_selector(selector: [u8; 4]) -> bool {
			Self::SELECTORS.binary_search(&selector).is_ok()
		}
		#[inline]
		#[allow(non_snake_case)]
		fn abi_decode_raw(selector: [u8; 4], data: &[u8]) -> alloy_sol_types::Result<Self> {
			static DECODE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<FooCalls>] = &[{
				fn generateTree(data: &[u8]) -> alloy_sol_types::Result<FooCalls> {
					<generateTreeCall as alloy_sol_types::SolCall>::abi_decode_raw(data).map(FooCalls::generateTree)
				}
				generateTree
			}];
			let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
				return Err(alloy_sol_types::Error::unknown_selector(
					<Self as alloy_sol_types::SolInterface>::NAME,
					selector,
				));
			};
			DECODE_SHIMS[idx](data)
		}
		#[inline]
		#[allow(non_snake_case)]
		fn abi_decode_raw_validate(selector: [u8; 4], data: &[u8]) -> alloy_sol_types::Result<Self> {
			static DECODE_VALIDATE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<FooCalls>] = &[{
				fn generateTree(data: &[u8]) -> alloy_sol_types::Result<FooCalls> {
					<generateTreeCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(data)
						.map(FooCalls::generateTree)
				}
				generateTree
			}];
			let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
				return Err(alloy_sol_types::Error::unknown_selector(
					<Self as alloy_sol_types::SolInterface>::NAME,
					selector,
				));
			};
			DECODE_VALIDATE_SHIMS[idx](data)
		}
		#[inline]
		fn abi_encoded_size(&self) -> usize {
			match self {
				Self::generateTree(inner) => <generateTreeCall as alloy_sol_types::SolCall>::abi_encoded_size(inner),
			}
		}
		#[inline]
		fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
			match self {
				Self::generateTree(inner) => <generateTreeCall as alloy_sol_types::SolCall>::abi_encode_raw(inner, out),
			}
		}
	}
	use alloy::contract as alloy_contract;
	/**Creates a new wrapper around an on-chain [`Foo`](self) contract instance.

	See the [wrapper's documentation](`FooInstance`) for more details.*/
	#[inline]
	pub const fn new<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		address: alloy_sol_types::private::Address,
		__provider: P,
	) -> FooInstance<P, N> {
		FooInstance::<P, N>::new(address, __provider)
	}
	/**Deploys this contract using the given `provider` and constructor arguments, if any.

	Returns a new instance of the contract, if the deployment was successful.

	For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
	#[inline]
	pub fn deploy<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		__provider: P,
	) -> impl ::core::future::Future<Output = alloy_contract::Result<FooInstance<P, N>>> {
		FooInstance::<P, N>::deploy(__provider)
	}
	/**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
	and constructor arguments, if any.

	This is a simple wrapper around creating a `RawCallBuilder` with the data set to
	the bytecode concatenated with the constructor's ABI-encoded arguments.*/
	#[inline]
	pub fn deploy_builder<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		__provider: P,
	) -> alloy_contract::RawCallBuilder<P, N> {
		FooInstance::<P, N>::deploy_builder(__provider)
	}
	/**A [`Foo`](self) instance.

	Contains type-safe methods for interacting with an on-chain instance of the
	[`Foo`](self) contract located at a given `address`, using a given
	provider `P`.

	If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
	documentation on how to provide it), the `deploy` and `deploy_builder` methods can
	be used to deploy a new instance of the contract.

	See the [module-level documentation](self) for all the available methods.*/
	#[derive(Clone)]
	pub struct FooInstance<P, N = alloy_contract::private::Ethereum> {
		address: alloy_sol_types::private::Address,
		provider: P,
		_network: ::core::marker::PhantomData<N>,
	}
	#[automatically_derived]
	impl<P, N> ::core::fmt::Debug for FooInstance<P, N> {
		#[inline]
		fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
			f.debug_tuple("FooInstance").field(&self.address).finish()
		}
	}
	/// Instantiation and getters/setters.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> FooInstance<P, N> {
		/**Creates a new wrapper around an on-chain [`Foo`](self) contract instance.

		See the [wrapper's documentation](`FooInstance`) for more details.*/
		#[inline]
		pub const fn new(address: alloy_sol_types::private::Address, __provider: P) -> Self {
			Self { address, provider: __provider, _network: ::core::marker::PhantomData }
		}
		/**Deploys this contract using the given `provider` and constructor arguments, if any.

		Returns a new instance of the contract, if the deployment was successful.

		For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
		#[inline]
		pub async fn deploy(__provider: P) -> alloy_contract::Result<FooInstance<P, N>> {
			let call_builder = Self::deploy_builder(__provider);
			let contract_address = call_builder.deploy().await?;
			Ok(Self::new(contract_address, call_builder.provider))
		}
		/**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
		and constructor arguments, if any.

		This is a simple wrapper around creating a `RawCallBuilder` with the data set to
		the bytecode concatenated with the constructor's ABI-encoded arguments.*/
		#[inline]
		pub fn deploy_builder(__provider: P) -> alloy_contract::RawCallBuilder<P, N> {
			alloy_contract::RawCallBuilder::new_raw_deploy(__provider, ::core::clone::Clone::clone(&BYTECODE))
		}
		/// Returns a reference to the address.
		#[inline]
		pub const fn address(&self) -> &alloy_sol_types::private::Address {
			&self.address
		}
		/// Sets the address.
		#[inline]
		pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
			self.address = address;
		}
		/// Sets the address and returns `self`.
		pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
			self.set_address(address);
			self
		}
		/// Returns a reference to the provider.
		#[inline]
		pub const fn provider(&self) -> &P {
			&self.provider
		}
	}
	impl<P: ::core::clone::Clone, N> FooInstance<&P, N> {
		/// Clones the provider and returns a new instance with the cloned provider.
		#[inline]
		pub fn with_cloned_provider(self) -> FooInstance<P, N> {
			FooInstance {
				address: self.address,
				provider: ::core::clone::Clone::clone(&self.provider),
				_network: ::core::marker::PhantomData,
			}
		}
	}
	/// Function calls.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> FooInstance<P, N> {
		/// Creates a new call builder using this contract instance's provider and address.
		///
		/// Note that the call can be any function call, not just those defined in this
		/// contract. Prefer using the other methods for building type-safe contract calls.
		pub fn call_builder<C: alloy_sol_types::SolCall>(&self, call: &C) -> alloy_contract::SolCallBuilder<&P, C, N> {
			alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
		}
		///Creates a new call builder for the [`generateTree`] function.
		pub fn generateTree(
			&self,
			leaves: alloy::sol_types::private::Vec<alloy::sol_types::private::FixedBytes<32>>,
		) -> alloy_contract::SolCallBuilder<&P, generateTreeCall, N> {
			self.call_builder(&generateTreeCall { leaves })
		}
	}
	/// Event filters.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> FooInstance<P, N> {
		/// Creates a new event filter using this contract instance's provider and address.
		///
		/// Note that the type can be any event, not just those defined in this contract.
		/// Prefer using the other methods for building type-safe event filters.
		pub fn event_filter<E: alloy_sol_types::SolEvent>(&self) -> alloy_contract::Event<&P, E, N> {
			alloy_contract::Event::new_sol(&self.provider, &self.address)
		}
	}
}
