/**

Generated by the following Solidity interface...
```solidity
interface PreconfStructs {
	error BeaconRootNotFound();
	error BlockIsNotFinalized();
	error BlockIsTooOld();
	error ChallengeAlreadyExists();
	error ChallengeDoesNotExist();
	error DelegationExpired();
	error EthTransferFailed();
	error FraudProofWindowActive();
	error IncorrectChallengeBond();
	error InvalidBlockHash();
	error InvalidBlockNumber();
	error InvalidParentBlockHash();
	error NotURC();
	error TransactionExcluded();
	error UnexpectedSigner();
	error WrongChallengerAddress();
	error WrongTransactionHashProof();
}
```

...which was generated by the following JSON ABI:
```json
[
  {
	"type": "error",
	"name": "BeaconRootNotFound",
	"inputs": []
  },
  {
	"type": "error",
	"name": "BlockIsNotFinalized",
	"inputs": []
  },
  {
	"type": "error",
	"name": "BlockIsTooOld",
	"inputs": []
  },
  {
	"type": "error",
	"name": "ChallengeAlreadyExists",
	"inputs": []
  },
  {
	"type": "error",
	"name": "ChallengeDoesNotExist",
	"inputs": []
  },
  {
	"type": "error",
	"name": "DelegationExpired",
	"inputs": []
  },
  {
	"type": "error",
	"name": "EthTransferFailed",
	"inputs": []
  },
  {
	"type": "error",
	"name": "FraudProofWindowActive",
	"inputs": []
  },
  {
	"type": "error",
	"name": "IncorrectChallengeBond",
	"inputs": []
  },
  {
	"type": "error",
	"name": "InvalidBlockHash",
	"inputs": []
  },
  {
	"type": "error",
	"name": "InvalidBlockNumber",
	"inputs": []
  },
  {
	"type": "error",
	"name": "InvalidParentBlockHash",
	"inputs": []
  },
  {
	"type": "error",
	"name": "NotURC",
	"inputs": []
  },
  {
	"type": "error",
	"name": "TransactionExcluded",
	"inputs": []
  },
  {
	"type": "error",
	"name": "UnexpectedSigner",
	"inputs": []
  },
  {
	"type": "error",
	"name": "WrongChallengerAddress",
	"inputs": []
  },
  {
	"type": "error",
	"name": "WrongTransactionHashProof",
	"inputs": []
  }
]
```*/
#[allow(
	non_camel_case_types,
	non_snake_case,
	clippy::pub_underscore_fields,
	clippy::style,
	clippy::empty_structs_with_brackets
)]
pub mod PreconfStructs {
	use super::*;
	use alloy::sol_types as alloy_sol_types;
	/// The creation / init bytecode of the contract.
    ///
    /// ```text
    ///0x
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"",
    );
	/// The runtime bytecode of the contract, as deployed on the network.
    ///
    /// ```text
    ///0x
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static DEPLOYED_BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"",
    );
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `BeaconRootNotFound()` and selector `0xe9697b68`.
	```solidity
	error BeaconRootNotFound();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct BeaconRootNotFound;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<BeaconRootNotFound> for UnderlyingRustTuple<'_> {
			fn from(value: BeaconRootNotFound) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for BeaconRootNotFound {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for BeaconRootNotFound {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "BeaconRootNotFound()";
			const SELECTOR: [u8; 4] = [233u8, 105u8, 123u8, 104u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `BlockIsNotFinalized()` and selector `0xb6144bff`.
	```solidity
	error BlockIsNotFinalized();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct BlockIsNotFinalized;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<BlockIsNotFinalized> for UnderlyingRustTuple<'_> {
			fn from(value: BlockIsNotFinalized) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for BlockIsNotFinalized {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for BlockIsNotFinalized {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "BlockIsNotFinalized()";
			const SELECTOR: [u8; 4] = [182u8, 20u8, 75u8, 255u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `BlockIsTooOld()` and selector `0x3373ade4`.
	```solidity
	error BlockIsTooOld();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct BlockIsTooOld;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<BlockIsTooOld> for UnderlyingRustTuple<'_> {
			fn from(value: BlockIsTooOld) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for BlockIsTooOld {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for BlockIsTooOld {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "BlockIsTooOld()";
			const SELECTOR: [u8; 4] = [51u8, 115u8, 173u8, 228u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `ChallengeAlreadyExists()` and selector `0x44504357`.
	```solidity
	error ChallengeAlreadyExists();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct ChallengeAlreadyExists;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<ChallengeAlreadyExists> for UnderlyingRustTuple<'_> {
			fn from(value: ChallengeAlreadyExists) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for ChallengeAlreadyExists {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for ChallengeAlreadyExists {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "ChallengeAlreadyExists()";
			const SELECTOR: [u8; 4] = [68u8, 80u8, 67u8, 87u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `ChallengeDoesNotExist()` and selector `0x03126e30`.
	```solidity
	error ChallengeDoesNotExist();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct ChallengeDoesNotExist;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<ChallengeDoesNotExist> for UnderlyingRustTuple<'_> {
			fn from(value: ChallengeDoesNotExist) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for ChallengeDoesNotExist {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for ChallengeDoesNotExist {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "ChallengeDoesNotExist()";
			const SELECTOR: [u8; 4] = [3u8, 18u8, 110u8, 48u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `DelegationExpired()` and selector `0x30d3ba07`.
	```solidity
	error DelegationExpired();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct DelegationExpired;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<DelegationExpired> for UnderlyingRustTuple<'_> {
			fn from(value: DelegationExpired) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for DelegationExpired {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for DelegationExpired {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "DelegationExpired()";
			const SELECTOR: [u8; 4] = [48u8, 211u8, 186u8, 7u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `EthTransferFailed()` and selector `0x6d963f88`.
	```solidity
	error EthTransferFailed();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct EthTransferFailed;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<EthTransferFailed> for UnderlyingRustTuple<'_> {
			fn from(value: EthTransferFailed) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for EthTransferFailed {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for EthTransferFailed {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "EthTransferFailed()";
			const SELECTOR: [u8; 4] = [109u8, 150u8, 63u8, 136u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `FraudProofWindowActive()` and selector `0x1f304cc1`.
	```solidity
	error FraudProofWindowActive();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct FraudProofWindowActive;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<FraudProofWindowActive> for UnderlyingRustTuple<'_> {
			fn from(value: FraudProofWindowActive) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for FraudProofWindowActive {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for FraudProofWindowActive {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "FraudProofWindowActive()";
			const SELECTOR: [u8; 4] = [31u8, 48u8, 76u8, 193u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `IncorrectChallengeBond()` and selector `0x9b8cc146`.
	```solidity
	error IncorrectChallengeBond();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct IncorrectChallengeBond;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<IncorrectChallengeBond> for UnderlyingRustTuple<'_> {
			fn from(value: IncorrectChallengeBond) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for IncorrectChallengeBond {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for IncorrectChallengeBond {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "IncorrectChallengeBond()";
			const SELECTOR: [u8; 4] = [155u8, 140u8, 193u8, 70u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `InvalidBlockHash()` and selector `0x3e068cb6`.
	```solidity
	error InvalidBlockHash();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct InvalidBlockHash;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<InvalidBlockHash> for UnderlyingRustTuple<'_> {
			fn from(value: InvalidBlockHash) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for InvalidBlockHash {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for InvalidBlockHash {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "InvalidBlockHash()";
			const SELECTOR: [u8; 4] = [62u8, 6u8, 140u8, 182u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `InvalidBlockNumber()` and selector `0x4e47846c`.
	```solidity
	error InvalidBlockNumber();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct InvalidBlockNumber;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<InvalidBlockNumber> for UnderlyingRustTuple<'_> {
			fn from(value: InvalidBlockNumber) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for InvalidBlockNumber {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for InvalidBlockNumber {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "InvalidBlockNumber()";
			const SELECTOR: [u8; 4] = [78u8, 71u8, 132u8, 108u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `InvalidParentBlockHash()` and selector `0x41f4d916`.
	```solidity
	error InvalidParentBlockHash();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct InvalidParentBlockHash;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<InvalidParentBlockHash> for UnderlyingRustTuple<'_> {
			fn from(value: InvalidParentBlockHash) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for InvalidParentBlockHash {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for InvalidParentBlockHash {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "InvalidParentBlockHash()";
			const SELECTOR: [u8; 4] = [65u8, 244u8, 217u8, 22u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `NotURC()` and selector `0xc7cb1eae`.
	```solidity
	error NotURC();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct NotURC;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<NotURC> for UnderlyingRustTuple<'_> {
			fn from(value: NotURC) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for NotURC {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for NotURC {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "NotURC()";
			const SELECTOR: [u8; 4] = [199u8, 203u8, 30u8, 174u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `TransactionExcluded()` and selector `0x094cec5f`.
	```solidity
	error TransactionExcluded();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct TransactionExcluded;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<TransactionExcluded> for UnderlyingRustTuple<'_> {
			fn from(value: TransactionExcluded) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for TransactionExcluded {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for TransactionExcluded {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "TransactionExcluded()";
			const SELECTOR: [u8; 4] = [9u8, 76u8, 236u8, 95u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `UnexpectedSigner()` and selector `0xaaaa9141`.
	```solidity
	error UnexpectedSigner();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct UnexpectedSigner;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnexpectedSigner> for UnderlyingRustTuple<'_> {
			fn from(value: UnexpectedSigner) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for UnexpectedSigner {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for UnexpectedSigner {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "UnexpectedSigner()";
			const SELECTOR: [u8; 4] = [170u8, 170u8, 145u8, 65u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `WrongChallengerAddress()` and selector `0x7546e8c1`.
	```solidity
	error WrongChallengerAddress();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct WrongChallengerAddress;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<WrongChallengerAddress> for UnderlyingRustTuple<'_> {
			fn from(value: WrongChallengerAddress) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for WrongChallengerAddress {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for WrongChallengerAddress {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "WrongChallengerAddress()";
			const SELECTOR: [u8; 4] = [117u8, 70u8, 232u8, 193u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `WrongTransactionHashProof()` and selector `0x88c5671e`.
	```solidity
	error WrongTransactionHashProof();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct WrongTransactionHashProof;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<WrongTransactionHashProof> for UnderlyingRustTuple<'_> {
			fn from(value: WrongTransactionHashProof) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for WrongTransactionHashProof {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for WrongTransactionHashProof {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "WrongTransactionHashProof()";
			const SELECTOR: [u8; 4] = [136u8, 197u8, 103u8, 30u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	///Container for all the [`PreconfStructs`](self) custom errors.
	#[derive(Clone, serde::Serialize, serde::Deserialize, Debug, PartialEq, Eq, Hash)]
	pub enum PreconfStructsErrors {
		#[allow(missing_docs)]
		BeaconRootNotFound(BeaconRootNotFound),
		#[allow(missing_docs)]
		BlockIsNotFinalized(BlockIsNotFinalized),
		#[allow(missing_docs)]
		BlockIsTooOld(BlockIsTooOld),
		#[allow(missing_docs)]
		ChallengeAlreadyExists(ChallengeAlreadyExists),
		#[allow(missing_docs)]
		ChallengeDoesNotExist(ChallengeDoesNotExist),
		#[allow(missing_docs)]
		DelegationExpired(DelegationExpired),
		#[allow(missing_docs)]
		EthTransferFailed(EthTransferFailed),
		#[allow(missing_docs)]
		FraudProofWindowActive(FraudProofWindowActive),
		#[allow(missing_docs)]
		IncorrectChallengeBond(IncorrectChallengeBond),
		#[allow(missing_docs)]
		InvalidBlockHash(InvalidBlockHash),
		#[allow(missing_docs)]
		InvalidBlockNumber(InvalidBlockNumber),
		#[allow(missing_docs)]
		InvalidParentBlockHash(InvalidParentBlockHash),
		#[allow(missing_docs)]
		NotURC(NotURC),
		#[allow(missing_docs)]
		TransactionExcluded(TransactionExcluded),
		#[allow(missing_docs)]
		UnexpectedSigner(UnexpectedSigner),
		#[allow(missing_docs)]
		WrongChallengerAddress(WrongChallengerAddress),
		#[allow(missing_docs)]
		WrongTransactionHashProof(WrongTransactionHashProof),
	}
	impl PreconfStructsErrors {
		/// All the selectors of this enum.
		///
		/// Note that the selectors might not be in the same order as the variants.
		/// No guarantees are made about the order of the selectors.
		///
		/// Prefer using `SolInterface` methods instead.
		pub const SELECTORS: &'static [[u8; 4usize]] = &[
			[3u8, 18u8, 110u8, 48u8],
			[9u8, 76u8, 236u8, 95u8],
			[31u8, 48u8, 76u8, 193u8],
			[48u8, 211u8, 186u8, 7u8],
			[51u8, 115u8, 173u8, 228u8],
			[62u8, 6u8, 140u8, 182u8],
			[65u8, 244u8, 217u8, 22u8],
			[68u8, 80u8, 67u8, 87u8],
			[78u8, 71u8, 132u8, 108u8],
			[109u8, 150u8, 63u8, 136u8],
			[117u8, 70u8, 232u8, 193u8],
			[136u8, 197u8, 103u8, 30u8],
			[155u8, 140u8, 193u8, 70u8],
			[170u8, 170u8, 145u8, 65u8],
			[182u8, 20u8, 75u8, 255u8],
			[199u8, 203u8, 30u8, 174u8],
			[233u8, 105u8, 123u8, 104u8],
		];
		/// The names of the variants in the same order as `SELECTORS`.
		pub const VARIANT_NAMES: &'static [&'static str] = &[
			::core::stringify!(ChallengeDoesNotExist),
			::core::stringify!(TransactionExcluded),
			::core::stringify!(FraudProofWindowActive),
			::core::stringify!(DelegationExpired),
			::core::stringify!(BlockIsTooOld),
			::core::stringify!(InvalidBlockHash),
			::core::stringify!(InvalidParentBlockHash),
			::core::stringify!(ChallengeAlreadyExists),
			::core::stringify!(InvalidBlockNumber),
			::core::stringify!(EthTransferFailed),
			::core::stringify!(WrongChallengerAddress),
			::core::stringify!(WrongTransactionHashProof),
			::core::stringify!(IncorrectChallengeBond),
			::core::stringify!(UnexpectedSigner),
			::core::stringify!(BlockIsNotFinalized),
			::core::stringify!(NotURC),
			::core::stringify!(BeaconRootNotFound),
		];
		/// The signatures in the same order as `SELECTORS`.
		pub const SIGNATURES: &'static [&'static str] = &[
			<ChallengeDoesNotExist as alloy_sol_types::SolError>::SIGNATURE,
			<TransactionExcluded as alloy_sol_types::SolError>::SIGNATURE,
			<FraudProofWindowActive as alloy_sol_types::SolError>::SIGNATURE,
			<DelegationExpired as alloy_sol_types::SolError>::SIGNATURE,
			<BlockIsTooOld as alloy_sol_types::SolError>::SIGNATURE,
			<InvalidBlockHash as alloy_sol_types::SolError>::SIGNATURE,
			<InvalidParentBlockHash as alloy_sol_types::SolError>::SIGNATURE,
			<ChallengeAlreadyExists as alloy_sol_types::SolError>::SIGNATURE,
			<InvalidBlockNumber as alloy_sol_types::SolError>::SIGNATURE,
			<EthTransferFailed as alloy_sol_types::SolError>::SIGNATURE,
			<WrongChallengerAddress as alloy_sol_types::SolError>::SIGNATURE,
			<WrongTransactionHashProof as alloy_sol_types::SolError>::SIGNATURE,
			<IncorrectChallengeBond as alloy_sol_types::SolError>::SIGNATURE,
			<UnexpectedSigner as alloy_sol_types::SolError>::SIGNATURE,
			<BlockIsNotFinalized as alloy_sol_types::SolError>::SIGNATURE,
			<NotURC as alloy_sol_types::SolError>::SIGNATURE,
			<BeaconRootNotFound as alloy_sol_types::SolError>::SIGNATURE,
		];
		/// Returns the signature for the given selector, if known.
		#[inline]
		pub fn signature_by_selector(selector: [u8; 4usize]) -> ::core::option::Option<&'static str> {
			match Self::SELECTORS.binary_search(&selector) {
				::core::result::Result::Ok(idx) => ::core::option::Option::Some(Self::SIGNATURES[idx]),
				::core::result::Result::Err(_) => ::core::option::Option::None,
			}
		}
		/// Returns the enum variant name for the given selector, if known.
		#[inline]
		pub fn name_by_selector(selector: [u8; 4usize]) -> ::core::option::Option<&'static str> {
			let sig = Self::signature_by_selector(selector)?;
			sig.split_once('(').map(|(name, _)| name)
		}
	}
	#[automatically_derived]
	impl alloy_sol_types::SolInterface for PreconfStructsErrors {
		const NAME: &'static str = "PreconfStructsErrors";
		const MIN_DATA_LENGTH: usize = 0usize;
		const COUNT: usize = 17usize;
		#[inline]
		fn selector(&self) -> [u8; 4] {
			match self {
				Self::BeaconRootNotFound(_) => <BeaconRootNotFound as alloy_sol_types::SolError>::SELECTOR,
				Self::BlockIsNotFinalized(_) => <BlockIsNotFinalized as alloy_sol_types::SolError>::SELECTOR,
				Self::BlockIsTooOld(_) => <BlockIsTooOld as alloy_sol_types::SolError>::SELECTOR,
				Self::ChallengeAlreadyExists(_) => <ChallengeAlreadyExists as alloy_sol_types::SolError>::SELECTOR,
				Self::ChallengeDoesNotExist(_) => <ChallengeDoesNotExist as alloy_sol_types::SolError>::SELECTOR,
				Self::DelegationExpired(_) => <DelegationExpired as alloy_sol_types::SolError>::SELECTOR,
				Self::EthTransferFailed(_) => <EthTransferFailed as alloy_sol_types::SolError>::SELECTOR,
				Self::FraudProofWindowActive(_) => <FraudProofWindowActive as alloy_sol_types::SolError>::SELECTOR,
				Self::IncorrectChallengeBond(_) => <IncorrectChallengeBond as alloy_sol_types::SolError>::SELECTOR,
				Self::InvalidBlockHash(_) => <InvalidBlockHash as alloy_sol_types::SolError>::SELECTOR,
				Self::InvalidBlockNumber(_) => <InvalidBlockNumber as alloy_sol_types::SolError>::SELECTOR,
				Self::InvalidParentBlockHash(_) => <InvalidParentBlockHash as alloy_sol_types::SolError>::SELECTOR,
				Self::NotURC(_) => <NotURC as alloy_sol_types::SolError>::SELECTOR,
				Self::TransactionExcluded(_) => <TransactionExcluded as alloy_sol_types::SolError>::SELECTOR,
				Self::UnexpectedSigner(_) => <UnexpectedSigner as alloy_sol_types::SolError>::SELECTOR,
				Self::WrongChallengerAddress(_) => <WrongChallengerAddress as alloy_sol_types::SolError>::SELECTOR,
				Self::WrongTransactionHashProof(_) => {
					<WrongTransactionHashProof as alloy_sol_types::SolError>::SELECTOR
				}
			}
		}
		#[inline]
		fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
			Self::SELECTORS.get(i).copied()
		}
		#[inline]
		fn valid_selector(selector: [u8; 4]) -> bool {
			Self::SELECTORS.binary_search(&selector).is_ok()
		}
		#[inline]
		#[allow(non_snake_case)]
		fn abi_decode_raw(selector: [u8; 4], data: &[u8]) -> alloy_sol_types::Result<Self> {
			static DECODE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<PreconfStructsErrors>] = &[
				{
					fn ChallengeDoesNotExist(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<ChallengeDoesNotExist as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::ChallengeDoesNotExist)
					}
					ChallengeDoesNotExist
				},
				{
					fn TransactionExcluded(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<TransactionExcluded as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::TransactionExcluded)
					}
					TransactionExcluded
				},
				{
					fn FraudProofWindowActive(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<FraudProofWindowActive as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::FraudProofWindowActive)
					}
					FraudProofWindowActive
				},
				{
					fn DelegationExpired(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<DelegationExpired as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::DelegationExpired)
					}
					DelegationExpired
				},
				{
					fn BlockIsTooOld(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<BlockIsTooOld as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::BlockIsTooOld)
					}
					BlockIsTooOld
				},
				{
					fn InvalidBlockHash(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<InvalidBlockHash as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::InvalidBlockHash)
					}
					InvalidBlockHash
				},
				{
					fn InvalidParentBlockHash(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<InvalidParentBlockHash as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::InvalidParentBlockHash)
					}
					InvalidParentBlockHash
				},
				{
					fn ChallengeAlreadyExists(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<ChallengeAlreadyExists as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::ChallengeAlreadyExists)
					}
					ChallengeAlreadyExists
				},
				{
					fn InvalidBlockNumber(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<InvalidBlockNumber as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::InvalidBlockNumber)
					}
					InvalidBlockNumber
				},
				{
					fn EthTransferFailed(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<EthTransferFailed as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::EthTransferFailed)
					}
					EthTransferFailed
				},
				{
					fn WrongChallengerAddress(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<WrongChallengerAddress as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::WrongChallengerAddress)
					}
					WrongChallengerAddress
				},
				{
					fn WrongTransactionHashProof(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<WrongTransactionHashProof as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::WrongTransactionHashProof)
					}
					WrongTransactionHashProof
				},
				{
					fn IncorrectChallengeBond(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<IncorrectChallengeBond as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::IncorrectChallengeBond)
					}
					IncorrectChallengeBond
				},
				{
					fn UnexpectedSigner(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<UnexpectedSigner as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::UnexpectedSigner)
					}
					UnexpectedSigner
				},
				{
					fn BlockIsNotFinalized(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<BlockIsNotFinalized as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::BlockIsNotFinalized)
					}
					BlockIsNotFinalized
				},
				{
					fn NotURC(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<NotURC as alloy_sol_types::SolError>::abi_decode_raw(data).map(PreconfStructsErrors::NotURC)
					}
					NotURC
				},
				{
					fn BeaconRootNotFound(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<BeaconRootNotFound as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(PreconfStructsErrors::BeaconRootNotFound)
					}
					BeaconRootNotFound
				},
			];
			let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
				return Err(alloy_sol_types::Error::unknown_selector(
					<Self as alloy_sol_types::SolInterface>::NAME,
					selector,
				));
			};
			DECODE_SHIMS[idx](data)
		}
		#[inline]
		#[allow(non_snake_case)]
		fn abi_decode_raw_validate(selector: [u8; 4], data: &[u8]) -> alloy_sol_types::Result<Self> {
			static DECODE_VALIDATE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<PreconfStructsErrors>] = &[
				{
					fn ChallengeDoesNotExist(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<ChallengeDoesNotExist as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::ChallengeDoesNotExist)
					}
					ChallengeDoesNotExist
				},
				{
					fn TransactionExcluded(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<TransactionExcluded as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::TransactionExcluded)
					}
					TransactionExcluded
				},
				{
					fn FraudProofWindowActive(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<FraudProofWindowActive as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::FraudProofWindowActive)
					}
					FraudProofWindowActive
				},
				{
					fn DelegationExpired(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<DelegationExpired as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::DelegationExpired)
					}
					DelegationExpired
				},
				{
					fn BlockIsTooOld(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<BlockIsTooOld as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::BlockIsTooOld)
					}
					BlockIsTooOld
				},
				{
					fn InvalidBlockHash(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<InvalidBlockHash as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::InvalidBlockHash)
					}
					InvalidBlockHash
				},
				{
					fn InvalidParentBlockHash(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<InvalidParentBlockHash as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::InvalidParentBlockHash)
					}
					InvalidParentBlockHash
				},
				{
					fn ChallengeAlreadyExists(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<ChallengeAlreadyExists as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::ChallengeAlreadyExists)
					}
					ChallengeAlreadyExists
				},
				{
					fn InvalidBlockNumber(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<InvalidBlockNumber as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::InvalidBlockNumber)
					}
					InvalidBlockNumber
				},
				{
					fn EthTransferFailed(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<EthTransferFailed as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::EthTransferFailed)
					}
					EthTransferFailed
				},
				{
					fn WrongChallengerAddress(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<WrongChallengerAddress as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::WrongChallengerAddress)
					}
					WrongChallengerAddress
				},
				{
					fn WrongTransactionHashProof(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<WrongTransactionHashProof as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::WrongTransactionHashProof)
					}
					WrongTransactionHashProof
				},
				{
					fn IncorrectChallengeBond(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<IncorrectChallengeBond as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::IncorrectChallengeBond)
					}
					IncorrectChallengeBond
				},
				{
					fn UnexpectedSigner(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<UnexpectedSigner as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::UnexpectedSigner)
					}
					UnexpectedSigner
				},
				{
					fn BlockIsNotFinalized(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<BlockIsNotFinalized as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::BlockIsNotFinalized)
					}
					BlockIsNotFinalized
				},
				{
					fn NotURC(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<NotURC as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::NotURC)
					}
					NotURC
				},
				{
					fn BeaconRootNotFound(data: &[u8]) -> alloy_sol_types::Result<PreconfStructsErrors> {
						<BeaconRootNotFound as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(PreconfStructsErrors::BeaconRootNotFound)
					}
					BeaconRootNotFound
				},
			];
			let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
				return Err(alloy_sol_types::Error::unknown_selector(
					<Self as alloy_sol_types::SolInterface>::NAME,
					selector,
				));
			};
			DECODE_VALIDATE_SHIMS[idx](data)
		}
		#[inline]
		fn abi_encoded_size(&self) -> usize {
			match self {
				Self::BeaconRootNotFound(inner) => {
					<BeaconRootNotFound as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::BlockIsNotFinalized(inner) => {
					<BlockIsNotFinalized as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::BlockIsTooOld(inner) => <BlockIsTooOld as alloy_sol_types::SolError>::abi_encoded_size(inner),
				Self::ChallengeAlreadyExists(inner) => {
					<ChallengeAlreadyExists as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::ChallengeDoesNotExist(inner) => {
					<ChallengeDoesNotExist as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::DelegationExpired(inner) => {
					<DelegationExpired as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::EthTransferFailed(inner) => {
					<EthTransferFailed as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::FraudProofWindowActive(inner) => {
					<FraudProofWindowActive as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::IncorrectChallengeBond(inner) => {
					<IncorrectChallengeBond as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::InvalidBlockHash(inner) => {
					<InvalidBlockHash as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::InvalidBlockNumber(inner) => {
					<InvalidBlockNumber as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::InvalidParentBlockHash(inner) => {
					<InvalidParentBlockHash as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::NotURC(inner) => <NotURC as alloy_sol_types::SolError>::abi_encoded_size(inner),
				Self::TransactionExcluded(inner) => {
					<TransactionExcluded as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::UnexpectedSigner(inner) => {
					<UnexpectedSigner as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::WrongChallengerAddress(inner) => {
					<WrongChallengerAddress as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::WrongTransactionHashProof(inner) => {
					<WrongTransactionHashProof as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
			}
		}
		#[inline]
		fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
			match self {
				Self::BeaconRootNotFound(inner) => {
					<BeaconRootNotFound as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::BlockIsNotFinalized(inner) => {
					<BlockIsNotFinalized as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::BlockIsTooOld(inner) => <BlockIsTooOld as alloy_sol_types::SolError>::abi_encode_raw(inner, out),
				Self::ChallengeAlreadyExists(inner) => {
					<ChallengeAlreadyExists as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::ChallengeDoesNotExist(inner) => {
					<ChallengeDoesNotExist as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::DelegationExpired(inner) => {
					<DelegationExpired as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::EthTransferFailed(inner) => {
					<EthTransferFailed as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::FraudProofWindowActive(inner) => {
					<FraudProofWindowActive as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::IncorrectChallengeBond(inner) => {
					<IncorrectChallengeBond as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::InvalidBlockHash(inner) => {
					<InvalidBlockHash as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::InvalidBlockNumber(inner) => {
					<InvalidBlockNumber as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::InvalidParentBlockHash(inner) => {
					<InvalidParentBlockHash as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::NotURC(inner) => <NotURC as alloy_sol_types::SolError>::abi_encode_raw(inner, out),
				Self::TransactionExcluded(inner) => {
					<TransactionExcluded as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::UnexpectedSigner(inner) => {
					<UnexpectedSigner as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::WrongChallengerAddress(inner) => {
					<WrongChallengerAddress as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::WrongTransactionHashProof(inner) => {
					<WrongTransactionHashProof as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
			}
		}
	}
	use alloy::contract as alloy_contract;
	/**Creates a new wrapper around an on-chain [`PreconfStructs`](self) contract instance.

	See the [wrapper's documentation](`PreconfStructsInstance`) for more details.*/
	#[inline]
	pub const fn new<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		address: alloy_sol_types::private::Address,
		__provider: P,
	) -> PreconfStructsInstance<P, N> {
		PreconfStructsInstance::<P, N>::new(address, __provider)
	}
	/**Deploys this contract using the given `provider` and constructor arguments, if any.

	Returns a new instance of the contract, if the deployment was successful.

	For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
	#[inline]
	pub fn deploy<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		__provider: P,
	) -> impl ::core::future::Future<Output = alloy_contract::Result<PreconfStructsInstance<P, N>>> {
		PreconfStructsInstance::<P, N>::deploy(__provider)
	}
	/**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
	and constructor arguments, if any.

	This is a simple wrapper around creating a `RawCallBuilder` with the data set to
	the bytecode concatenated with the constructor's ABI-encoded arguments.*/
	#[inline]
	pub fn deploy_builder<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		__provider: P,
	) -> alloy_contract::RawCallBuilder<P, N> {
		PreconfStructsInstance::<P, N>::deploy_builder(__provider)
	}
	/**A [`PreconfStructs`](self) instance.

	Contains type-safe methods for interacting with an on-chain instance of the
	[`PreconfStructs`](self) contract located at a given `address`, using a given
	provider `P`.

	If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
	documentation on how to provide it), the `deploy` and `deploy_builder` methods can
	be used to deploy a new instance of the contract.

	See the [module-level documentation](self) for all the available methods.*/
	#[derive(Clone)]
	pub struct PreconfStructsInstance<P, N = alloy_contract::private::Ethereum> {
		address: alloy_sol_types::private::Address,
		provider: P,
		_network: ::core::marker::PhantomData<N>,
	}
	#[automatically_derived]
	impl<P, N> ::core::fmt::Debug for PreconfStructsInstance<P, N> {
		#[inline]
		fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
			f.debug_tuple("PreconfStructsInstance").field(&self.address).finish()
		}
	}
	/// Instantiation and getters/setters.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> PreconfStructsInstance<P, N> {
		/**Creates a new wrapper around an on-chain [`PreconfStructs`](self) contract instance.

		See the [wrapper's documentation](`PreconfStructsInstance`) for more details.*/
		#[inline]
		pub const fn new(address: alloy_sol_types::private::Address, __provider: P) -> Self {
			Self { address, provider: __provider, _network: ::core::marker::PhantomData }
		}
		/**Deploys this contract using the given `provider` and constructor arguments, if any.

		Returns a new instance of the contract, if the deployment was successful.

		For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
		#[inline]
		pub async fn deploy(__provider: P) -> alloy_contract::Result<PreconfStructsInstance<P, N>> {
			let call_builder = Self::deploy_builder(__provider);
			let contract_address = call_builder.deploy().await?;
			Ok(Self::new(contract_address, call_builder.provider))
		}
		/**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
		and constructor arguments, if any.

		This is a simple wrapper around creating a `RawCallBuilder` with the data set to
		the bytecode concatenated with the constructor's ABI-encoded arguments.*/
		#[inline]
		pub fn deploy_builder(__provider: P) -> alloy_contract::RawCallBuilder<P, N> {
			alloy_contract::RawCallBuilder::new_raw_deploy(__provider, ::core::clone::Clone::clone(&BYTECODE))
		}
		/// Returns a reference to the address.
		#[inline]
		pub const fn address(&self) -> &alloy_sol_types::private::Address {
			&self.address
		}
		/// Sets the address.
		#[inline]
		pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
			self.address = address;
		}
		/// Sets the address and returns `self`.
		pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
			self.set_address(address);
			self
		}
		/// Returns a reference to the provider.
		#[inline]
		pub const fn provider(&self) -> &P {
			&self.provider
		}
	}
	impl<P: ::core::clone::Clone, N> PreconfStructsInstance<&P, N> {
		/// Clones the provider and returns a new instance with the cloned provider.
		#[inline]
		pub fn with_cloned_provider(self) -> PreconfStructsInstance<P, N> {
			PreconfStructsInstance {
				address: self.address,
				provider: ::core::clone::Clone::clone(&self.provider),
				_network: ::core::marker::PhantomData,
			}
		}
	}
	/// Function calls.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> PreconfStructsInstance<P, N> {
		/// Creates a new call builder using this contract instance's provider and address.
		///
		/// Note that the call can be any function call, not just those defined in this
		/// contract. Prefer using the other methods for building type-safe contract calls.
		pub fn call_builder<C: alloy_sol_types::SolCall>(&self, call: &C) -> alloy_contract::SolCallBuilder<&P, C, N> {
			alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
		}
	}
	/// Event filters.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> PreconfStructsInstance<P, N> {
		/// Creates a new event filter using this contract instance's provider and address.
		///
		/// Note that the type can be any event, not just those defined in this contract.
		/// Prefer using the other methods for building type-safe event filters.
		pub fn event_filter<E: alloy_sol_types::SolEvent>(&self) -> alloy_contract::Event<&P, E, N> {
			alloy_contract::Event::new_sol(&self.provider, &self.address)
		}
	}
}
