/**

Generated by the following Solidity interface...
```solidity
interface TransactionDecoder {
	error InvalidFieldCount();
	error InvalidSignatureLength();
	error InvalidYParity();
	error NoSignature();
	error UnsupportedTxType();
}
```

...which was generated by the following JSON ABI:
```json
[
  {
	"type": "error",
	"name": "InvalidFieldCount",
	"inputs": []
  },
  {
	"type": "error",
	"name": "InvalidSignatureLength",
	"inputs": []
  },
  {
	"type": "error",
	"name": "InvalidYParity",
	"inputs": []
  },
  {
	"type": "error",
	"name": "NoSignature",
	"inputs": []
  },
  {
	"type": "error",
	"name": "UnsupportedTxType",
	"inputs": []
  }
]
```*/
#[allow(
	non_camel_case_types,
	non_snake_case,
	clippy::pub_underscore_fields,
	clippy::style,
	clippy::empty_structs_with_brackets
)]
pub mod TransactionDecoder {
	use super::*;
	use alloy::sol_types as alloy_sol_types;
	/// The creation / init bytecode of the contract.
    ///
    /// ```text
    ///0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212206d16e5c846ef39cd332dddcea97c193235f16f78bc2d371c4c2d62a7250dfe9164736f6c63430008190033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"`U`2`\x0B\x82\x82\x829\x80Q_\x1A`s\x14`&WcNH{q`\xE0\x1B_R_`\x04R`$_\xFD[0_R`s\x81S\x82\x81\xF3\xFEs\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x000\x14`\x80`@R_\x80\xFD\xFE\xA2dipfsX\"\x12 m\x16\xE5\xC8F\xEF9\xCD3-\xDD\xCE\xA9|\x1925\xF1ox\xBC-7\x1CL-b\xA7%\r\xFE\x91dsolcC\0\x08\x19\x003",
    );
	/// The runtime bytecode of the contract, as deployed on the network.
    ///
    /// ```text
    ///0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212206d16e5c846ef39cd332dddcea97c193235f16f78bc2d371c4c2d62a7250dfe9164736f6c63430008190033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static DEPLOYED_BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"s\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x000\x14`\x80`@R_\x80\xFD\xFE\xA2dipfsX\"\x12 m\x16\xE5\xC8F\xEF9\xCD3-\xDD\xCE\xA9|\x1925\xF1ox\xBC-7\x1CL-b\xA7%\r\xFE\x91dsolcC\0\x08\x19\x003",
    );
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `InvalidFieldCount()` and selector `0xc2871a37`.
	```solidity
	error InvalidFieldCount();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct InvalidFieldCount;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<InvalidFieldCount> for UnderlyingRustTuple<'_> {
			fn from(value: InvalidFieldCount) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for InvalidFieldCount {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for InvalidFieldCount {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "InvalidFieldCount()";
			const SELECTOR: [u8; 4] = [194u8, 135u8, 26u8, 55u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `InvalidSignatureLength()` and selector `0x4be6321b`.
	```solidity
	error InvalidSignatureLength();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct InvalidSignatureLength;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<InvalidSignatureLength> for UnderlyingRustTuple<'_> {
			fn from(value: InvalidSignatureLength) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for InvalidSignatureLength {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for InvalidSignatureLength {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "InvalidSignatureLength()";
			const SELECTOR: [u8; 4] = [75u8, 230u8, 50u8, 27u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `InvalidYParity()` and selector `0x541b3bce`.
	```solidity
	error InvalidYParity();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct InvalidYParity;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<InvalidYParity> for UnderlyingRustTuple<'_> {
			fn from(value: InvalidYParity) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for InvalidYParity {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for InvalidYParity {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "InvalidYParity()";
			const SELECTOR: [u8; 4] = [84u8, 27u8, 59u8, 206u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `NoSignature()` and selector `0xd466bd15`.
	```solidity
	error NoSignature();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct NoSignature;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<NoSignature> for UnderlyingRustTuple<'_> {
			fn from(value: NoSignature) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for NoSignature {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for NoSignature {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "NoSignature()";
			const SELECTOR: [u8; 4] = [212u8, 102u8, 189u8, 21u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	#[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
	/**Custom error with signature `UnsupportedTxType()` and selector `0xdf87b546`.
	```solidity
	error UnsupportedTxType();
	```*/
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
	#[derive(Clone)]
	pub struct UnsupportedTxType;
	#[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields, clippy::style)]
	const _: () = {
		use alloy::sol_types as alloy_sol_types;
		#[doc(hidden)]
		#[allow(dead_code)]
		type UnderlyingSolTuple<'a> = ();
		#[doc(hidden)]
		type UnderlyingRustTuple<'a> = ();
		#[cfg(test)]
		#[allow(dead_code, unreachable_patterns)]
		fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
			match _t {
				alloy_sol_types::private::AssertTypeEq::<<UnderlyingSolTuple as alloy_sol_types::SolType>::RustType>(
					_,
				) => {}
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnsupportedTxType> for UnderlyingRustTuple<'_> {
			fn from(value: UnsupportedTxType) -> Self {
				()
			}
		}
		#[automatically_derived]
		#[doc(hidden)]
		impl ::core::convert::From<UnderlyingRustTuple<'_>> for UnsupportedTxType {
			fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
				Self
			}
		}
		#[automatically_derived]
		impl alloy_sol_types::SolError for UnsupportedTxType {
			type Parameters<'a> = UnderlyingSolTuple<'a>;
			type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
			const SIGNATURE: &'static str = "UnsupportedTxType()";
			const SELECTOR: [u8; 4] = [223u8, 135u8, 181u8, 70u8];
			#[inline]
			fn new<'a>(tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType) -> Self {
				tuple.into()
			}
			#[inline]
			fn tokenize(&self) -> Self::Token<'_> {
				()
			}
			#[inline]
			fn abi_decode_raw_validate(data: &[u8]) -> alloy_sol_types::Result<Self> {
				<Self::Parameters<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(data).map(Self::new)
			}
		}
	};
	///Container for all the [`TransactionDecoder`](self) custom errors.
	#[derive(Clone, serde::Serialize, serde::Deserialize, Debug, PartialEq, Eq, Hash)]
	pub enum TransactionDecoderErrors {
		#[allow(missing_docs)]
		InvalidFieldCount(InvalidFieldCount),
		#[allow(missing_docs)]
		InvalidSignatureLength(InvalidSignatureLength),
		#[allow(missing_docs)]
		InvalidYParity(InvalidYParity),
		#[allow(missing_docs)]
		NoSignature(NoSignature),
		#[allow(missing_docs)]
		UnsupportedTxType(UnsupportedTxType),
	}
	impl TransactionDecoderErrors {
		/// All the selectors of this enum.
		///
		/// Note that the selectors might not be in the same order as the variants.
		/// No guarantees are made about the order of the selectors.
		///
		/// Prefer using `SolInterface` methods instead.
		pub const SELECTORS: &'static [[u8; 4usize]] = &[
			[75u8, 230u8, 50u8, 27u8],
			[84u8, 27u8, 59u8, 206u8],
			[194u8, 135u8, 26u8, 55u8],
			[212u8, 102u8, 189u8, 21u8],
			[223u8, 135u8, 181u8, 70u8],
		];
		/// The names of the variants in the same order as `SELECTORS`.
		pub const VARIANT_NAMES: &'static [&'static str] = &[
			::core::stringify!(InvalidSignatureLength),
			::core::stringify!(InvalidYParity),
			::core::stringify!(InvalidFieldCount),
			::core::stringify!(NoSignature),
			::core::stringify!(UnsupportedTxType),
		];
		/// The signatures in the same order as `SELECTORS`.
		pub const SIGNATURES: &'static [&'static str] = &[
			<InvalidSignatureLength as alloy_sol_types::SolError>::SIGNATURE,
			<InvalidYParity as alloy_sol_types::SolError>::SIGNATURE,
			<InvalidFieldCount as alloy_sol_types::SolError>::SIGNATURE,
			<NoSignature as alloy_sol_types::SolError>::SIGNATURE,
			<UnsupportedTxType as alloy_sol_types::SolError>::SIGNATURE,
		];
		/// Returns the signature for the given selector, if known.
		#[inline]
		pub fn signature_by_selector(selector: [u8; 4usize]) -> ::core::option::Option<&'static str> {
			match Self::SELECTORS.binary_search(&selector) {
				::core::result::Result::Ok(idx) => ::core::option::Option::Some(Self::SIGNATURES[idx]),
				::core::result::Result::Err(_) => ::core::option::Option::None,
			}
		}
		/// Returns the enum variant name for the given selector, if known.
		#[inline]
		pub fn name_by_selector(selector: [u8; 4usize]) -> ::core::option::Option<&'static str> {
			let sig = Self::signature_by_selector(selector)?;
			sig.split_once('(').map(|(name, _)| name)
		}
	}
	#[automatically_derived]
	impl alloy_sol_types::SolInterface for TransactionDecoderErrors {
		const NAME: &'static str = "TransactionDecoderErrors";
		const MIN_DATA_LENGTH: usize = 0usize;
		const COUNT: usize = 5usize;
		#[inline]
		fn selector(&self) -> [u8; 4] {
			match self {
				Self::InvalidFieldCount(_) => <InvalidFieldCount as alloy_sol_types::SolError>::SELECTOR,
				Self::InvalidSignatureLength(_) => <InvalidSignatureLength as alloy_sol_types::SolError>::SELECTOR,
				Self::InvalidYParity(_) => <InvalidYParity as alloy_sol_types::SolError>::SELECTOR,
				Self::NoSignature(_) => <NoSignature as alloy_sol_types::SolError>::SELECTOR,
				Self::UnsupportedTxType(_) => <UnsupportedTxType as alloy_sol_types::SolError>::SELECTOR,
			}
		}
		#[inline]
		fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
			Self::SELECTORS.get(i).copied()
		}
		#[inline]
		fn valid_selector(selector: [u8; 4]) -> bool {
			Self::SELECTORS.binary_search(&selector).is_ok()
		}
		#[inline]
		#[allow(non_snake_case)]
		fn abi_decode_raw(selector: [u8; 4], data: &[u8]) -> alloy_sol_types::Result<Self> {
			static DECODE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors>] = &[
				{
					fn InvalidSignatureLength(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<InvalidSignatureLength as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(TransactionDecoderErrors::InvalidSignatureLength)
					}
					InvalidSignatureLength
				},
				{
					fn InvalidYParity(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<InvalidYParity as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(TransactionDecoderErrors::InvalidYParity)
					}
					InvalidYParity
				},
				{
					fn InvalidFieldCount(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<InvalidFieldCount as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(TransactionDecoderErrors::InvalidFieldCount)
					}
					InvalidFieldCount
				},
				{
					fn NoSignature(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<NoSignature as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(TransactionDecoderErrors::NoSignature)
					}
					NoSignature
				},
				{
					fn UnsupportedTxType(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<UnsupportedTxType as alloy_sol_types::SolError>::abi_decode_raw(data)
							.map(TransactionDecoderErrors::UnsupportedTxType)
					}
					UnsupportedTxType
				},
			];
			let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
				return Err(alloy_sol_types::Error::unknown_selector(
					<Self as alloy_sol_types::SolInterface>::NAME,
					selector,
				));
			};
			DECODE_SHIMS[idx](data)
		}
		#[inline]
		#[allow(non_snake_case)]
		fn abi_decode_raw_validate(selector: [u8; 4], data: &[u8]) -> alloy_sol_types::Result<Self> {
			static DECODE_VALIDATE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors>] = &[
				{
					fn InvalidSignatureLength(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<InvalidSignatureLength as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(TransactionDecoderErrors::InvalidSignatureLength)
					}
					InvalidSignatureLength
				},
				{
					fn InvalidYParity(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<InvalidYParity as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(TransactionDecoderErrors::InvalidYParity)
					}
					InvalidYParity
				},
				{
					fn InvalidFieldCount(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<InvalidFieldCount as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(TransactionDecoderErrors::InvalidFieldCount)
					}
					InvalidFieldCount
				},
				{
					fn NoSignature(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<NoSignature as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(TransactionDecoderErrors::NoSignature)
					}
					NoSignature
				},
				{
					fn UnsupportedTxType(data: &[u8]) -> alloy_sol_types::Result<TransactionDecoderErrors> {
						<UnsupportedTxType as alloy_sol_types::SolError>::abi_decode_raw_validate(data)
							.map(TransactionDecoderErrors::UnsupportedTxType)
					}
					UnsupportedTxType
				},
			];
			let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
				return Err(alloy_sol_types::Error::unknown_selector(
					<Self as alloy_sol_types::SolInterface>::NAME,
					selector,
				));
			};
			DECODE_VALIDATE_SHIMS[idx](data)
		}
		#[inline]
		fn abi_encoded_size(&self) -> usize {
			match self {
				Self::InvalidFieldCount(inner) => {
					<InvalidFieldCount as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::InvalidSignatureLength(inner) => {
					<InvalidSignatureLength as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
				Self::InvalidYParity(inner) => <InvalidYParity as alloy_sol_types::SolError>::abi_encoded_size(inner),
				Self::NoSignature(inner) => <NoSignature as alloy_sol_types::SolError>::abi_encoded_size(inner),
				Self::UnsupportedTxType(inner) => {
					<UnsupportedTxType as alloy_sol_types::SolError>::abi_encoded_size(inner)
				}
			}
		}
		#[inline]
		fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
			match self {
				Self::InvalidFieldCount(inner) => {
					<InvalidFieldCount as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::InvalidSignatureLength(inner) => {
					<InvalidSignatureLength as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::InvalidYParity(inner) => {
					<InvalidYParity as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
				Self::NoSignature(inner) => <NoSignature as alloy_sol_types::SolError>::abi_encode_raw(inner, out),
				Self::UnsupportedTxType(inner) => {
					<UnsupportedTxType as alloy_sol_types::SolError>::abi_encode_raw(inner, out)
				}
			}
		}
	}
	use alloy::contract as alloy_contract;
	/**Creates a new wrapper around an on-chain [`TransactionDecoder`](self) contract instance.

	See the [wrapper's documentation](`TransactionDecoderInstance`) for more details.*/
	#[inline]
	pub const fn new<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		address: alloy_sol_types::private::Address,
		__provider: P,
	) -> TransactionDecoderInstance<P, N> {
		TransactionDecoderInstance::<P, N>::new(address, __provider)
	}
	/**Deploys this contract using the given `provider` and constructor arguments, if any.

	Returns a new instance of the contract, if the deployment was successful.

	For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
	#[inline]
	pub fn deploy<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		__provider: P,
	) -> impl ::core::future::Future<Output = alloy_contract::Result<TransactionDecoderInstance<P, N>>> {
		TransactionDecoderInstance::<P, N>::deploy(__provider)
	}
	/**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
	and constructor arguments, if any.

	This is a simple wrapper around creating a `RawCallBuilder` with the data set to
	the bytecode concatenated with the constructor's ABI-encoded arguments.*/
	#[inline]
	pub fn deploy_builder<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
		__provider: P,
	) -> alloy_contract::RawCallBuilder<P, N> {
		TransactionDecoderInstance::<P, N>::deploy_builder(__provider)
	}
	/**A [`TransactionDecoder`](self) instance.

	Contains type-safe methods for interacting with an on-chain instance of the
	[`TransactionDecoder`](self) contract located at a given `address`, using a given
	provider `P`.

	If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
	documentation on how to provide it), the `deploy` and `deploy_builder` methods can
	be used to deploy a new instance of the contract.

	See the [module-level documentation](self) for all the available methods.*/
	#[derive(Clone)]
	pub struct TransactionDecoderInstance<P, N = alloy_contract::private::Ethereum> {
		address: alloy_sol_types::private::Address,
		provider: P,
		_network: ::core::marker::PhantomData<N>,
	}
	#[automatically_derived]
	impl<P, N> ::core::fmt::Debug for TransactionDecoderInstance<P, N> {
		#[inline]
		fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
			f.debug_tuple("TransactionDecoderInstance").field(&self.address).finish()
		}
	}
	/// Instantiation and getters/setters.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> TransactionDecoderInstance<P, N> {
		/**Creates a new wrapper around an on-chain [`TransactionDecoder`](self) contract instance.

		See the [wrapper's documentation](`TransactionDecoderInstance`) for more details.*/
		#[inline]
		pub const fn new(address: alloy_sol_types::private::Address, __provider: P) -> Self {
			Self { address, provider: __provider, _network: ::core::marker::PhantomData }
		}
		/**Deploys this contract using the given `provider` and constructor arguments, if any.

		Returns a new instance of the contract, if the deployment was successful.

		For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
		#[inline]
		pub async fn deploy(__provider: P) -> alloy_contract::Result<TransactionDecoderInstance<P, N>> {
			let call_builder = Self::deploy_builder(__provider);
			let contract_address = call_builder.deploy().await?;
			Ok(Self::new(contract_address, call_builder.provider))
		}
		/**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
		and constructor arguments, if any.

		This is a simple wrapper around creating a `RawCallBuilder` with the data set to
		the bytecode concatenated with the constructor's ABI-encoded arguments.*/
		#[inline]
		pub fn deploy_builder(__provider: P) -> alloy_contract::RawCallBuilder<P, N> {
			alloy_contract::RawCallBuilder::new_raw_deploy(__provider, ::core::clone::Clone::clone(&BYTECODE))
		}
		/// Returns a reference to the address.
		#[inline]
		pub const fn address(&self) -> &alloy_sol_types::private::Address {
			&self.address
		}
		/// Sets the address.
		#[inline]
		pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
			self.address = address;
		}
		/// Sets the address and returns `self`.
		pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
			self.set_address(address);
			self
		}
		/// Returns a reference to the provider.
		#[inline]
		pub const fn provider(&self) -> &P {
			&self.provider
		}
	}
	impl<P: ::core::clone::Clone, N> TransactionDecoderInstance<&P, N> {
		/// Clones the provider and returns a new instance with the cloned provider.
		#[inline]
		pub fn with_cloned_provider(self) -> TransactionDecoderInstance<P, N> {
			TransactionDecoderInstance {
				address: self.address,
				provider: ::core::clone::Clone::clone(&self.provider),
				_network: ::core::marker::PhantomData,
			}
		}
	}
	/// Function calls.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> TransactionDecoderInstance<P, N> {
		/// Creates a new call builder using this contract instance's provider and address.
		///
		/// Note that the call can be any function call, not just those defined in this
		/// contract. Prefer using the other methods for building type-safe contract calls.
		pub fn call_builder<C: alloy_sol_types::SolCall>(&self, call: &C) -> alloy_contract::SolCallBuilder<&P, C, N> {
			alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
		}
	}
	/// Event filters.
	impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network> TransactionDecoderInstance<P, N> {
		/// Creates a new event filter using this contract instance's provider and address.
		///
		/// Note that the type can be any event, not just those defined in this contract.
		/// Prefer using the other methods for building type-safe event filters.
		pub fn event_filter<E: alloy_sol_types::SolEvent>(&self) -> alloy_contract::Event<&P, E, N> {
			alloy_contract::Event::new_sol(&self.provider, &self.address)
		}
	}
}
